sonar.projectKey=TubagusAulia_simop-kjpp
sonar.organization=tubagusaulia
sonar.host.url=https://sonarcloud.io

sonar.language=php
sonar.sources=app
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=test-report.xml

sonar.exclusions=vendor/**,storage/**,bootstrap/cache/**,public/**
